version: '3.8'

services:
  gcloud:
    build:
      context: gcloud
      dockerfile: Dockerfile
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    cgroup:
      aa

  java:
    build:
      context: java
      dockerfile: Dockerfile
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    depends_on:
      - gcloud
    cgroup:
      aa
